/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_appsync_graphqlEndpoint": "https://zok7ijcg6fd3pduduyc6rjt6ei.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-h4ocnd6mcvapffsulewqkkdery",
    "aws_cognito_identity_pool_id": "ca-central-1:a956c954-5e64-4446-ad2b-359257a03c70",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_MzHeTLd3X",
    "aws_user_pools_web_client_id": "48ai7kk9mce7nsrhm95isq3a58",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
